export const professionalSkills = [
  "JavaScript: ES6+ features",
  "React",
  "Redux (Toolkit)",
  "Redux-Saga",
  "React Router",
  "React Hooks",
  "React Context",
  "Styled-components",
  "Responsive Web Design",
  "CSS Grid",
  "CSS Flexbox",
  "Leaflet",
  "PHP 7.x",
  "Symfony 4.x",
  "Doctrine",
  "MySQL",
  "Twig",
  "E-commerce",
  "Semantic & accessible HTML",
  "LocalStorage",
  "Teamwork",
  "Immutbility",
  "Error handling",
  "Working with API (fetch,axios)",
  // eslint-disable-next-line
  "Promises, Async/Await",
  "Git",
  "Bitbucket",
  "Trello",
  "NPM",
];

export const projectSkills = [
  "React-Bootstrap",
  "CSS BEM convention",
  "Markdown",
  "GitHub Pull Requests & Review",
  "Scrum",
  "Node.js",
  "Express",
  "MongoDB (Mongoose)",
  "JWT",
  "Yarn",
];

export const futureSkills = [
  "TypeScript",
  "Jest",
  "Next.js",
];