export const skills = [
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "Teamwork",
  "Markdown",
  "Immutbility",
  "CSS BEM convention",
  "CSS Grid",
  "CSS Flexbox",
  "React Router",
  "Redux-Saga",
  "Redux (Toolkit)",
  "React Hooks",
  "Error handling",
  "Working with API (fetch,axios)",
  "JavaScript: ES6+ features",
  "Promises, Async/Await",
  "GitHub Pull Requests & Review",
  "Trello",
  "Scrum",
  "NPM",
  "Yarn",
  "React",
  "React-Bootstrap",
  "Git",
  "Node.js",
  "Express",
  "MongoDB (Mongoose)",
  "JWT",
  "LocalStorage",
];

export const futureSkills = [
  "Cypress",
  "TypeScript",
  "React Context",
  "React Internationalization",
  "GraphQL",

];